version: '3.4'

services:
  todo-list:
    image: todo-list
    ports:
      - "80:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test@Password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - mssql
    networks:
      - private
      - public
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=StrongPwd123
      - ACCEPT_EULA=Y
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - private
      - public

volumes:
  mssqldata:

networks:
  private:
  public: