kind: ConfigMap
apiVersion: v1
metadata:
  name: code4nothing-cm
  namespace: code4nothing
  labels:
    app: code4nothing
    service: code4nothing
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: code4nothing
  namespace: code4nothing
  labels:
    app: code4nothing
    service: code4nothing
spec:
  replicas: 1
  selector:
    matchLabels:
      service: code4nothing
  template:
    metadata:
      labels:
        app: code4nothing
        service: code4nothing
    spec:
      containers:
        - name: code4nothing-api
          image: code4nothing/code4nothing.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: code4nothing-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

kind: Service
apiVersion: v1
metadata:
  name: code4nothing-api
  namespace: code4nothing
  labels:
    app: code4nothing
    service: code4nothing
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
      protocol: TCP
      name: http
  selector:
    service: code4nothing
